//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol
{
    using System;
    using System.Collections.Generic;
    
    public partial class itf_cc
    {
        public int id { get; set; }
        public string parametr { get; set; }
        public string wartosc { get; set; }
        public string opis { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
