//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol
{
    using System;
    using System.Collections.Generic;
    
    public partial class meldunki
    {
        public int id { get; set; }
        public int id_zlecenie { get; set; }
        public int zmiana { get; set; }
        public Nullable<System.DateTime> data_meldunku { get; set; }
        public int ilosc { get; set; }
        public Nullable<int> ilosc_n { get; set; }
        public Nullable<int> ilosc_nn { get; set; }
        public string opw { get; set; }
        public System.DateTime czasw { get; set; }
        public string opm { get; set; }
        public System.DateTime czasm { get; set; }
    }
}
