//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecoplastol
{
    using System;
    using System.Collections.Generic;
    
    public partial class wyroby
    {
        public int id { get; set; }
        public string wyrob_kod { get; set; }
        public string wyrob_kod_indeks { get; set; }
        public string wyrob_kod_opis { get; set; }
        public Nullable<int> wyrob_typ { get; set; }
        public Nullable<int> wyrob_il_w_op_zb { get; set; }
        public Nullable<int> wyrob_waga_op { get; set; }
        public Nullable<int> wyrob_waga_1szt { get; set; }
        public Nullable<int> wyrob_zakres_sdr { get; set; }
        public Nullable<int> wyrob_zast_zaworu { get; set; }
        public Nullable<int> wyrob_rodzaj_drutu { get; set; }
        public Nullable<int> itf_kategoria { get; set; }
        public Nullable<int> itf_znak1 { get; set; }
        public Nullable<int> itf_znak2 { get; set; }
        public Nullable<int> itf_icc { get; set; }
        public Nullable<int> itf_cc1 { get; set; }
        public Nullable<int> itf_cc2 { get; set; }
        public Nullable<int> itf_smin { get; set; }
        public Nullable<int> itf_smax { get; set; }
        public Nullable<int> itf_trn { get; set; }
        public string itf_prn { get; set; }
        public string itf_rez { get; set; }
        public Nullable<int> itf_odch { get; set; }
        public string itf_cz1 { get; set; }
        public string itf_cz2 { get; set; }
        public string itf_ke { get; set; }
        public Nullable<int> trace_znak1 { get; set; }
        public Nullable<int> trace_znak2 { get; set; }
        public Nullable<int> trace_kategoria { get; set; }
        public Nullable<int> trace_smin { get; set; }
        public Nullable<int> trace_smax { get; set; }
        public string trace_partia { get; set; }
        public Nullable<int> trace_producent { get; set; }
        public Nullable<int> trace_sdr { get; set; }
        public Nullable<int> trace_pe_m { get; set; }
        public Nullable<int> trace_material { get; set; }
        public Nullable<int> trace_pe_o { get; set; }
        public Nullable<int> trace_mfr { get; set; }
        public string opw { get; set; }
        public Nullable<System.DateTime> czasw { get; set; }
        public string opm { get; set; }
        public Nullable<System.DateTime> czasm { get; set; }
    }
}
